version: "3"
services:
    nodejs:
        build:
            context: .
            dockerfile: Dockerfile.nodejs
        ports:
            - "6379:6379"
        env_file:
            - .env.prod
        environment:
            - NODE_ENV=production

    nginx:
        image: nginx
        ports:
            - "8080:8080"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./public:/usr/share/nginx/html
        depends_on:
            - nodejs
